## import numpy as np

In [1]:
import numpy as np

## create an array of 10 zeros

In [2]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## create an array of 10 ones

In [3]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## create an array with 10 fives

In [4]:
a = np.ones((1,10))
print(a*5)
#or

b = np.full((1,10),5)
print(b)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
[[5 5 5 5 5 5 5 5 5 5]]


## create an array with values from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## create an array with even numbers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## create a 3x3 identity matrix

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## use numpy random to generate a random number between 0 and 1

In [9]:
np.random.randn(1)

array([-0.00933819])

In [10]:
np.random.randn(25)

array([ 1.45822583,  0.14151379,  1.07622817, -0.32229792, -0.32173645,
       -1.0187747 ,  0.21724438, -1.03749066,  0.88666554, -1.26211461,
        0.78881397,  0.57430253,  0.22104028,  0.14223112, -0.55170371,
        0.51287795,  0.4383043 , -0.62260154,  0.610645  , -1.17695206,
       -1.53936614, -0.87894097,  1.50537023,  0.69030805, -1.22695234])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
np.random.randn(25)

array([-0.25434797,  0.58018565, -0.22294146,  1.2251613 , -1.11992135,
        1.18778148, -0.02434226, -1.39953445,  0.80717082,  0.23709212,
        0.11817541,  0.44130895, -1.39285798,  0.65250796,  0.77701786,
        0.21692117, -0.63444522, -0.99917209,  0.0269415 , -0.68535236,
        0.90874776, -0.20042226,  0.59208169, -0.69747231, -0.99462225])

In [12]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [13]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [14]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [30]:
print(mat[2:,1:])
print("\n")
print("\n")
print(mat[3:,2:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]




[[18 19 20]
 [23 24 25]]


In [33]:
print(mat[4,:])

[21 22 23 24 25]


In [34]:
mat.sum()

325

In [36]:
mat.std()

7.211102550927978

In [42]:
mat.std(axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])