# Numpy Arrays

In [2]:
import numpy as np
print(np.__version__)

1.19.5


In [3]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
a = np.ones(5)
print(a*5)

[5. 5. 5. 5. 5.]


In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# identity matrix

In [12]:
#identity matrix is a useful matrix when dealing with linear algebra problems 
#it return a matrix that is diagonally matching in number
#it is a 2 dimensional matix, where the number of rows == the number of columns
# you have a diagonals of 1 and everything else is zero
#that is why it only takes a single digit as the argument

In [13]:
 np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# random

In [14]:
"""the rand will create an array of the given shape passed in and it will populate it with random samples from a given
distribution using zeros and ones"""
#if i want an array of random numbers uniformally distributed using zeros and ones
np.random.rand(5)

array([0.84342339, 0.9372326 , 0.82904072, 0.08997342, 0.46153363])

In [15]:
#a 5 x 5 matrix of random numbers
np.random.rand(5,5)

array([[0.12954438, 0.97876519, 0.52138707, 0.06657793, 0.68556208],
       [0.13114759, 0.08490258, 0.3491676 , 0.98347895, 0.57667495],
       [0.14646792, 0.92167222, 0.26193774, 0.37906057, 0.74547009],
       [0.55667491, 0.03182667, 0.5621241 , 0.95824929, 0.85555883],
       [0.80769724, 0.39768188, 0.17506348, 0.77596883, 0.82593324]])

In [16]:
#this will return a number from a standard normal distribution centered around 0 
np.random.randn(4,4)

array([[-0.16149566, -0.08262047,  1.33251462,  0.28276729],
       [ 0.92139632,  0.61884203, -1.12792041, -0.51191771],
       [ 0.70797559,  0.81385426, -0.02433442,  0.54824478],
       [-0.08525473, -0.10432466, -0.31460539,  0.62313234]])

In [17]:
#this will return random integers from the lowest to the highest
"""to get a random integer between 1 and 100"""
print(np.random.randint(1,100))
# you can specify the number of random integers you want using a third argument
print(np.random.randint(1,100,10))

47
[18 62 30 59 26 68 86 22 68 15]


In [18]:
ranarr = np.random.randint(0,10,20)
ranarr

array([0, 3, 8, 8, 1, 5, 0, 0, 8, 0, 5, 0, 9, 9, 2, 2, 1, 4, 0, 5])

In [16]:
arr = np.arange(0,20)

In [17]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# to get the max and min value of array 

In [21]:
a = arr.max()
b = arr.min()
print("max and min values are {} and {} respectively".format(a,b))

max and min values are 19 and 0 respectively


In [22]:
#to return th index location of the max value
arr.argmax()

19

In [18]:
#to return the index location of the min value
arr.argmin()

0

In [24]:
ranarr.min()

0

In [25]:
ranarr.max()

9

In [26]:
ranarr.argmax()

12

In [27]:
ranarr.argmin()

0

In [28]:
arr.shape

(20,)

In [29]:
arr = arr.reshape(5,4)

In [30]:
arr.shape

(5, 4)

In [31]:
arr.dtype

dtype('int32')

In [20]:
# if you dont want to call the random.randint import it 

In [21]:
from numpy.random import randint

In [23]:
randint(2,10)

9

# Numpy Indexing

In [35]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

8

In [37]:
arr[10]

10

In [38]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [39]:
arr[:3]

array([0, 1, 2])

In [40]:
arr[3:4]

array([3])

In [41]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [42]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# Numpy Operations
#### . Array with Array
#### . Array with Scalars
#### . Universal Array Functions

In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [46]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [48]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [49]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [50]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [51]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [52]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [53]:
np.max(arr)

10

In [54]:
np.min(arr)

0

In [55]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [56]:
np.log(arr)

C:\Users\TOBBY\AppData\Local\Temp/ipykernel_6204/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])